34 - add emergency info
GCTC-NTGC/gc-accessibility-passport pull request #102
Opened 2022-05-19 19:43 UTC by brindasasi

2022-05-24 21:02 UTC, mnigh requested changes
Good start. Please see my suggestions and comments.

2022-05-24 21:02 UTC, mnigh commented on pages/emergency-info.tsx
> +import { Input, Submit, TextArea } from "../components/formComponents";
```suggestion
import { Input, TextArea } from "../components/formComponents";
```

2022-05-24 21:02 UTC, mnigh commented on pages/emergency-info.tsx
> +    <Layout
Based on [design](https://www.figma.com/file/SqRfWwcyuclFvGCq47zJf6/Passport---V5.0.0?node-id=2%3A11), missing breadcrumbs: _My passport / Emergency Information_

2022-05-24 21:02 UTC, mnigh commented on pages/emergency-info.tsx
> +                    <a data-h2-margin="b(right, m)">{"Upload"}</a>
Is this meant to be `<input type="file" />`?

2022-05-24 21:02 UTC, mnigh commented on pages/emergency-info.tsx
> +                <div
Consider replacing these two file rows with for alignment and responsiveness:

```
                <div
                  data-h2-margin="b(top-bottom, s)"
                  data-h2-display="b(block) s(flex)"
                >
                  <span data-h2-margin="b(right, xs)">
                    <PaperClipIcon style={{ width: "1.2rem" }}> </PaperClipIcon>
                  </span>
                  <Link href="#">
                    <a data-h2-margin="b(right, xs)">
                      {intl.formatMessage({
                        defaultMessage: "my_paramedical_needs.pdf(3MB)",
                      })}
                    </a>
                  </Link>
                  <Link href={"#"}>
                    <a
                      data-h2-margin="b(left, auto)"
                      data-h2-display="b(block)"
                    >
                      Remove
                    </a>
                  </Link>
                </div>
                <div
                  data-h2-margin="b(top-bottom, s)"
                  data-h2-display="b(block) s(flex)"
                >
                  <span data-h2-margin="b(right, xs)">
                    <PaperClipIcon style={{ width: "1.2rem" }}> </PaperClipIcon>
                  </span>
                  <Link href="#">
                    <a data-h2-margin="b(right, xs)">
                      {intl.formatMessage({
                        defaultMessage: "my_evacuation_plan.pdf(3MB)",
                      })}
                    </a>
                  </Link>
                  <Link href={"#"}>
                    <a
                      data-h2-margin="b(left, auto)"
                      data-h2-display="b(block)"
                    >
                      Remove
                    </a>
                  </Link>
                </div>
```

2022-05-24 21:02 UTC, mnigh commented on pages/emergency-info.tsx
> +const bold = (msg: string): React.ReactNode => (
Consider changing the name of this to `strong` and using <strong> tags instead of css within the function itself.

2022-06-06 15:22 UTC, yonikid15 requested changes
Left some minor suggested changes, but overall looks good!

2022-06-06 15:22 UTC, yonikid15 commented on pages/passport/emergency-info.tsx
> +        },
```suggestion
      crumbs={[
        {
          title: intl.formatMessage({
            defaultMessage: "My passport",
            description: "Breadcrumb title.",
          }),
          href: "/passport",
        },
```

2022-06-06 15:22 UTC, yonikid15 commented on pages/passport/emergency-info.tsx
> +};
```suggestion
type FormValues = {
  description: string;
  firstName: string;
  lastName: string;
  telephone: string;
};
```

2022-06-06 15:22 UTC, yonikid15 commented on pages/passport/emergency-info.tsx
> +              <p>
```suggestion
              <p data-h2-margin="b(top, none)">
```

2022-06-06 15:22 UTC, yonikid15 commented on pages/passport/emergency-info.tsx
> +            </h4>
```suggestion
          <div>
            <h4 data-h2-font-size="b(h4)" data-h2-margin="b(top-bottom, none)">
              {intl.formatMessage({
                defaultMessage: "Permissions",
              })}
            </h4>
```

2022-06-08 19:34 UTC, yonikid15 approved these changes
Love it

2022-06-08 19:34 UTC, merged