67 - add breadcrumbs draft version
GCTC-NTGC/gc-accessibility-passport pull request #94
Opened 2022-05-16 14:24 UTC by brindasasi

2022-05-19 14:50 UTC, mnigh commented
@brindasasi could you resolve the merge conflicts before i start my review?

2022-05-19 20:07 UTC, yonikid15 requested changes
Nice work so far Brinda. Great job incorporating the crumbs prop in the `<Layout />` component. It makes it easier to add custom names. The styling could use some work though. Can you add some padding around it and a lightgray background color to match the design. Also, there's a few pages that have incorrect breadcrumbs. I'll try to flag them all.

Question: Why did you move those files into a `permissions` folder?

Also, this isn't part of the scope of this issue, but I think if we want to do this right though were going to have to completely refactor the file structure so that it matches the Breadcrumbs. I made a list of what it would look like (i think):

Sitemap:
(User not logged in)
home `(pages/index.tsx)`
home -> login `(pages/login.tsx)`
home -> register `(pages/register.tsx)`

(User logged in and not manager)
my account `(pages/account.tsx)` **Change account-management.tsx to account.tsx**
my passport `(pages/passport/index.tsx)` **index.tsx will be the new passport.tsx**
my passport -> emergency information `(pages/passport/emergency-info.tsx)`
my passport -> my manager's information `(pages/passport/manager-info.tsx)`
my passport -> share my passport `(pages/passport/share-my-passport.tsx)`
my passport -> manage permissions `(pages/passport/manage-permissions.tsx)`
my passport -> identify a new barrier `(pages/passport/barriers/identify-a-barrier.tsx)`
my passport -> identify a new barrier -> propose solutions `(pages/passport/barriers/solutions/identify-a-solution.tsx)`
my passport -> my barriers(?) -> Barrier: Noise in the workplace `(pages/passport/barriers/review-barrier.tsx)`
my passport -> my barriers(?) -> Barrier: Noise in the workplace -> Solution: Noise cancelling headphones `(pages/passport/barriers/solutions/review-solution.tsx)` **Change solutions/view.tsx to review-solution.tsx**

(User logged in and is manager)
my dashboard `(pages/manager/dashboard.tsx)`
my dashboard -> my employees(?) -> Frank Turot `(pages/manager/view-employee-passport.tsx)`
my dashboard -> my employees(?) -> Frank Turot -> Barrier: Noise in the Workplace `(pages/manager/view-employee-barrier.tsx)`
my dashboard -> my employees(?) -> Frank Turot -> Barrier: Noise in the Workplace -> Solution: Noise cancelling headphones `(pages/manager/view-employee-solution.tsx)`

2022-05-19 20:07 UTC, yonikid15 commented on components/Layout.tsx
> +    },
Only the login and register pages should have the Home breadcrumb according to the design.

2022-05-19 20:07 UTC, yonikid15 commented on helpers/accessibilityPassportRoutes.ts
> +import path from "path-browserify";
This file can be deleted since it's not being used.

2022-05-19 20:07 UTC, yonikid15 commented on helpers/localize.ts
> +import { createPath, parsePath, Path } from "history";
This file can be deleted since it's not being used.

2022-05-19 20:07 UTC, yonikid15 commented on package.json
> +    "history": "^5.3.0",
All three dependencies (`history`, `path-browserify`, and `@types/path-browserify` can be removed since they aren't being used.

2022-05-19 20:07 UTC, yonikid15 commented on pages/manager/view-action-solution.tsx
> +          href: "/manager/view-action-solution",
The `href` should be removed here since the user is on this page.

2022-05-19 20:07 UTC, yonikid15 commented on pages/manager/view-employee-barrier.tsx
> +          href: "/manager/view-employee-barrier",
The `href` should be removed from the last elemen, since the user is on this page. Can you do it for all the other pages as well.

2022-05-24 14:09 UTC, mnigh commented
@yonikid15 I have updated the route structure to match what you had suggested here as well as addressed your other comments. Please let me know if I've missed anything, thanks.

2022-05-26 14:01 UTC, yonikid15 requested changes
I added some suggested changes for the `crumbs` props in some pages. Just so they match the wireframe. There's also some files changes I want to make, but to make this less confusing I'll make another issue after this is done.

2022-05-26 14:01 UTC, yonikid15 commented on pages/passport/share-my-passport.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My passport", href: "/passport" },
        { title: "Share my passport" },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/passport/manager-info.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My passport", href: "/passport" },
        { title: "Manager Info" },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/account.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "Manage your account" },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/passport/barriers/solutions/identify-a-solution.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My passport", href: "/passport" },
        {
          title: "Identify a barrier",
          href: "/passport/barriers/identify-a-barrier",
        },
        {
          title: "Propose Solutions",
        },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/passport/barriers/solutions/identify-a-solution-2.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My passport", href: "/passport" },
        {
          title: "Identify a barrier",
          href: "/passport/barriers/identify-a-barrier",
        },
        {
          title: "Propose Solutions",
        },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/passport/barriers/solutions/review-solution.tsx
> +          href: "/passport/barriers/solutions/review-solution",
```suggestion
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/manager/view-employee-barrier.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My Dashboard", href: "/manager/manager-dashboard" },
        { title: "Frank Turot", href: "/manager/view-employee-passport" },
        {
          title: "Noise in the workplace",
        },
      ]}
```

2022-05-26 14:01 UTC, yonikid15 commented on pages/manager/view-employee-solution.tsx
> +      ]}
```suggestion
      crumbs={[
        { title: "My Dashboard", href: "/manager/manager-dashboard" },
        { title: "Frank Turot", href: "/manager/view-employee-passport" },
        {
          title: "Noise in the workplace",
          href: "/manager/view-employee-barrier",
        },
        {
          title: "Noise cancelling headphones",
        },
      ]}
```

2022-05-26 14:34 UTC, yonikid15 requested changes

2022-05-26 14:34 UTC, yonikid15 commented on components/Breadcrumbs.tsx
> +      data-h2-bg-color="b(lightgray)"
```suggestion
      data-h2-padding="b(all, m) s(right-left, xl)"
      data-h2-bg-color="b(lightblue)"
```

2022-05-26 14:34 UTC, yonikid15 commented on components/Breadcrumbs.tsx
> +      data-h2-bg-color="b(lightgray)"
Last cosmetic change!

2022-05-26 14:47 UTC, yonikid15 approved these changes
🎉

2022-05-26 14:47 UTC, merged